# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HrlloWorldService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HrlloWorldService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17HrlloWorldService.proto\"!\n\x11HelloWorldRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x12HelloWorldResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\nHelloWorld\x12\x34\n\x07SendSms\x12\x12.HelloWorldRequest\x1a\x13.HelloWorldResponse\"\x00\x62\x06proto3')
)




_HELLOWORLDREQUEST = _descriptor.Descriptor(
  name='HelloWorldRequest',
  full_name='HelloWorldRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HelloWorldRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=60,
)


_HELLOWORLDRESPONSE = _descriptor.Descriptor(
  name='HelloWorldResponse',
  full_name='HelloWorldResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='HelloWorldResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['HelloWorldRequest'] = _HELLOWORLDREQUEST
DESCRIPTOR.message_types_by_name['HelloWorldResponse'] = _HELLOWORLDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloWorldRequest = _reflection.GeneratedProtocolMessageType('HelloWorldRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOWORLDREQUEST,
  __module__ = 'HrlloWorldService_pb2'
  # @@protoc_insertion_point(class_scope:HelloWorldRequest)
  ))
_sym_db.RegisterMessage(HelloWorldRequest)

HelloWorldResponse = _reflection.GeneratedProtocolMessageType('HelloWorldResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLOWORLDRESPONSE,
  __module__ = 'HrlloWorldService_pb2'
  # @@protoc_insertion_point(class_scope:HelloWorldResponse)
  ))
_sym_db.RegisterMessage(HelloWorldResponse)



_HELLOWORLD = _descriptor.ServiceDescriptor(
  name='HelloWorld',
  full_name='HelloWorld',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=101,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendSms',
    full_name='HelloWorld.SendSms',
    index=0,
    containing_service=None,
    input_type=_HELLOWORLDREQUEST,
    output_type=_HELLOWORLDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOWORLD)

DESCRIPTOR.services_by_name['HelloWorld'] = _HELLOWORLD

# @@protoc_insertion_point(module_scope)
